version: "3"

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx
        restart: on-failure
        ports:
          - "80:80"
          - "443:443"
        networks:
          - inception

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb
        restart: on-failure
        env_file:
          - .env
        volumes:
          - databasefile:/var/lib/mysql
        expose:
          - "3306"
        networks:
          - inception
volumes:
    databasefile:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/mariadb
    wordpressfile:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wordpress

networks:
    inception:
        driver: bridge